### ISSUE TITLE
Adafruit CC3000 discontinued problem

### ISSUE THREAD

**Issue by cumarit** [cytan299/field_derotator#3]
How can I replace it with the Adafruit WINC1500?
Thank you.
Marcello

**Comment by cytan299** [comment]
When I look at the winc1500 when compared to cc3000, it looks like the IRQ and CS pins are not at the same location. You'll have to modify them on the winc1500 board accordingly. The code will have to be updated to so that it uses the winc1500 library and not the cc3000 library.

I don't think it is too difficult for you to do it.
